### ISSUE TITLE
fix: very_good_dart_package disappeared for a minute

### ISSUE THREAD

**Issue by renancaraujo** [brick-hub/brickhub.dev#78]
When trying to publish a version for `very_good_dart_package`, I got this error:

```
Do you want to publish very_good_dart_package 0.3.0? (y/N) Yes
✗ Publishing very_good_dart_package 0.3.0 (30.4s)
An unknown error occurred.
```

After that, the brickhub website indicated the package as "not found".

After trying to publish again, the brick is back in the air.

**Comment by felangel** [comment]
Hi @renancaraujo 👋 
Thanks for opening an issue!

I took a look at the logs and it looked like a timeout occurred (it appears the upload request exceeded the 30s timeout). I recommend closing this for now since it seems your re-upload worked and we can revisit this if it occurs again. Let me know what you think and sorry for the inconvenience!
